# Generated by Django 4.1.7 on 2023-03-19 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailusers', '0011_userprofile_dismissibles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css_file', models.CharField(blank=True, max_length=100)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_theme', to='wagtailusers.userprofile')),
            ],
        ),
    ]
